name: appnationdoggy
description: "A new Flutter project."

publish_to: "none" 


version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path_provider: ^2.0.11
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  flutter_bloc: ^8.1.6
  dio_cache_interceptor_hive_store: ^3.2.2
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: GalanoGrotesqueAlt
      fonts:
        - asset: assets/fonts/GalanoGrotesqueAltBold.otf
          weight: 700
        - asset: assets/fonts/GalanoGrotesqueAltBlack.otf
          weight: 900
        - asset: assets/fonts/GalanoGrotesqueAltBlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/GalanoGrotesqueAltBoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/GalanoGrotesqueAltExtraBold.otf
          weight: 800
        - asset: assets/fonts/GalanoGrotesqueAltExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/GalanoGrotesqueAltExtraLight.otf
          weight: 200
        - asset: assets/fonts/GalanoGrotesqueAltExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/GalanoGrotesqueAltHeavy.otf
          weight: 900
        - asset: assets/fonts/GalanoGrotesqueAltHeavyItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/GalanoGrotesqueAltItalic.otf
          style: italic
        - asset: assets/fonts/GalanoGrotesqueAltLight.otf
          weight: 300
        - asset: assets/fonts/GalanoGrotesqueAltLightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/GalanoGrotesqueAltMedium.otf
          weight: 500
        - asset: assets/fonts/GalanoGrotesqueAltMediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/GalanoGrotesqueAltRegular.otf
        - asset: assets/fonts/GalanoGrotesqueAltSemiBold.otf
          weight: 600
        - asset: assets/fonts/GalanoGrotesqueAltSemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/GalanoGrotesqueAltThin.otf
          weight: 100
        - asset: assets/fonts/GalanoGrotesqueAltThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/GalanoGrotesqueBlack.otf
          weight: 900
        - asset: assets/fonts/GalanoGrotesqueBlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/GalanoGrotesqueBold.otf
          weight: 700
        - asset: assets/fonts/GalanoGrotesqueBoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/GalanoGrotesqueExtraBold.otf
          weight: 800
        - asset: assets/fonts/GalanoGrotesqueExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/GalanoGrotesqueExtraLight.otf
          weight: 200
        - asset: assets/fonts/GalanoGrotesqueExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/GalanoGrotesqueHeavy.otf
          weight: 900
        - asset: assets/fonts/GalanoGrotesqueHeavyItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/GalanoGrotesqueItalic.otf
          style: italic
        - asset: assets/fonts/GalanoGrotesqueLight.otf
          weight: 300
        - asset: assets/fonts/GalanoGrotesqueLightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/GalanoGrotesqueMedium.otf
          weight: 500
        - asset: assets/fonts/GalanoGrotesqueMediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/GalanoGrotesqueRegular.otf
        - asset: assets/fonts/GalanoGrotesqueSemiBold.otf
          weight: 600
        - asset: assets/fonts/GalanoGrotesqueSemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/GalanoGrotesqueThin.otf
          weight: 100
        - asset: assets/fonts/GalanoGrotesqueThinItalic.otf
          weight: 100
          style: italic
